name: maui
description: Literacy application for children

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  image_picker: ^0.4.0
  xmlstream: ^0.10.0
  sqflite: any
  uuid: ^0.5.0
  path_provider: ^0.4.0
  tuple: ^1.0.1
  firebase_database: ^0.4.1
  firebase_storage: ^0.2.0
  json_annotation: ^0.2.2
  audioplayer: ^0.4.0
  fluttie: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  build_runner: ^0.7.6
  json_serializable: ^0.3.2
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/database.db
    - assets/chimple_logo.png
    - assets/apple.png
    - assets/Boy.png
    - assets/imageCoordinatesInfo.json
    - assets/imageCoordinatesInfo2.json
    - assets/apple.ogg
    - assets/dice_3.png
    - assets/dice5.gif
    - assets/Shapes.png
    - assets/koala_neutral.png
    - assets/koala_happy.png
    - assets/koala_sad.png
    - assets/animations/koala_happy.json
    - assets/animations/koala_sad.json
    - assets/animations/horse_sad2.json
    - assets/animations/goat_sad2.json
    - assets/animations/goat_sad3.json
    - assets/animations/zebra_face.json
    - assets/animations/happybirthday.json
    - assets/animations/owl_happy2.json
    - assets/animations/owl_happy3.json
    - assets/animations/test.json
    - assets/animations/heart.json
    - assets/animations/ball.json
    - assets/hoodie/reflex.png
    - assets/hoodie/2x/reflex.png
    - assets/hoodie/3x/reflex.png
    - assets/hoodie/4x/reflex.png
    - assets/hoodie/abacus.png
    - assets/hoodie/2x/abacus.png
    - assets/hoodie/3x/abacus.png
    - assets/hoodie/4x/abacus.png
    - assets/hoodie/bingo.png
    - assets/hoodie/2x/bingo.png
    - assets/hoodie/3x/bingo.png
    - assets/hoodie/4x/bingo.png
    - assets/hoodie/calculate_numbers.png
    - assets/hoodie/2x/calculate_numbers.png
    - assets/hoodie/3x/calculate_numbers.png
    - assets/hoodie/4x/calculate_numbers.png
    - assets/hoodie/casino.png
    - assets/hoodie/2x/casino.png
    - assets/hoodie/3x/casino.png
    - assets/hoodie/4x/casino.png
    - assets/hoodie/circle_words.png
    - assets/hoodie/2x/circle_words.png
    - assets/hoodie/3x/circle_words.png
    - assets/hoodie/4x/circle_words.png
    - assets/hoodie/clue_game.png
    - assets/hoodie/2x/clue_game.png
    - assets/hoodie/3x/clue_game.png
    - assets/hoodie/4x/clue_game.png
    - assets/hoodie/connect_the_dots.png
    - assets/hoodie/2x/connect_the_dots.png
    - assets/hoodie/3x/connect_the_dots.png
    - assets/hoodie/4x/connect_the_dots.png
    - assets/hoodie/crossword.png
    - assets/hoodie/2x/crossword.png
    - assets/hoodie/3x/crossword.png
    - assets/hoodie/4x/crossword.png
    - assets/hoodie/draw_challenge.png
    - assets/hoodie/2x/draw_challenge.png
    - assets/hoodie/3x/draw_challenge.png
    - assets/hoodie/4x/draw_challenge.png
    - assets/hoodie/drawing.png
    - assets/hoodie/2x/drawing.png
    - assets/hoodie/3x/drawing.png
    - assets/hoodie/4x/drawing.png
    - assets/hoodie/fill_in_the_blanks.png
    - assets/hoodie/2x/fill_in_the_blanks.png
    - assets/hoodie/3x/fill_in_the_blanks.png
    - assets/hoodie/4x/fill_in_the_blanks.png
    - assets/hoodie/fill_number.png
    - assets/hoodie/2x/fill_number.png
    - assets/hoodie/3x/fill_number.png
    - assets/hoodie/4x/fill_number.png
    - assets/hoodie/first_word.png
    - assets/hoodie/2x/first_word.png
    - assets/hoodie/3x/first_word.png
    - assets/hoodie/4x/first_word.png
    - assets/hoodie/friend_word.png
    - assets/hoodie/2x/friend_word.png
    - assets/hoodie/3x/friend_word.png
    - assets/hoodie/4x/friend_word.png
    - assets/hoodie/guess.png
    - assets/hoodie/2x/guess.png
    - assets/hoodie/3x/guess.png
    - assets/hoodie/4x/guess.png
    - assets/hoodie/identify.png
    - assets/hoodie/2x/identify.png
    - assets/hoodie/3x/identify.png
    - assets/hoodie/4x/identify.png
    - assets/hoodie/identify.png
    - assets/hoodie/2x/identify.png
    - assets/hoodie/3x/identify.png
    - assets/hoodie/4x/identify.png
    - assets/hoodie/match_the_following.png
    - assets/hoodie/2x/match_the_following.png
    - assets/hoodie/3x/match_the_following.png
    - assets/hoodie/4x/match_the_following.png
    - assets/hoodie/memory.png
    - assets/hoodie/2x/memory.png
    - assets/hoodie/3x/memory.png
    - assets/hoodie/4x/memory.png
    - assets/hoodie/order_it.png
    - assets/hoodie/2x/order_it.png
    - assets/hoodie/3x/order_it.png
    - assets/hoodie/4x/order_it.png
    - assets/hoodie/quiz.png
    - assets/hoodie/2x/quiz.png
    - assets/hoodie/3x/quiz.png
    - assets/hoodie/4x/quiz.png
    - assets/hoodie/spin_wheel.png
    - assets/hoodie/2x/spin_wheel.png
    - assets/hoodie/3x/spin_wheel.png
    - assets/hoodie/4x/spin_wheel.png
    - assets/hoodie/tables.png
    - assets/hoodie/2x/tables.png
    - assets/hoodie/3x/tables.png
    - assets/hoodie/4x/tables.png
    - assets/hoodie/tap_home.png
    - assets/hoodie/2x/tap_home.png
    - assets/hoodie/3x/tap_home.png
    - assets/hoodie/4x/tap_home.png
    - assets/hoodie/tap_wrong.png
    - assets/hoodie/2x/tap_wrong.png
    - assets/hoodie/3x/tap_wrong.png
    - assets/hoodie/4x/tap_wrong.png 
    - assets/hoodie/true_or_false.png
    - assets/hoodie/2x/true_or_false.png
    - assets/hoodie/3x/true_or_false.png
    - assets/hoodie/4x/true_or_false.png
    
    #happy
    - assets/hoodie/reflex_happy.png
    - assets/hoodie/2x/reflex_happy.png
    - assets/hoodie/3x/reflex_happy.png
    - assets/hoodie/4x/reflex_happy.png
    - assets/hoodie/abacus_happy.png
    - assets/hoodie/2x/abacus_happy.png
    - assets/hoodie/3x/abacus_happy.png
    - assets/hoodie/4x/abacus_happy.png
    - assets/hoodie/bingo_happy.png
    - assets/hoodie/2x/bingo_happy.png
    - assets/hoodie/3x/bingo_happy.png
    - assets/hoodie/4x/bingo_happy.png
    - assets/hoodie/calculate_numbers_happy.png
    - assets/hoodie/2x/calculate_numbers_happy.png
    - assets/hoodie/3x/calculate_numbers_happy.png
    - assets/hoodie/4x/calculate_numbers_happy.png
    - assets/hoodie/casino_happy.png
    - assets/hoodie/2x/casino_happy.png
    - assets/hoodie/3x/casino_happy.png
    - assets/hoodie/4x/casino_happy.png
    - assets/hoodie/circle_words_happy.png
    - assets/hoodie/2x/circle_words_happy.png
    - assets/hoodie/3x/circle_words_happy.png
    - assets/hoodie/4x/circle_words_happy.png
    - assets/hoodie/clue_game_happy.png
    - assets/hoodie/2x/clue_game_happy.png
    - assets/hoodie/3x/clue_game_happy.png
    - assets/hoodie/4x/clue_game_happy.png
    - assets/hoodie/connect_the_dots_happy.png
    - assets/hoodie/2x/connect_the_dots_happy.png
    - assets/hoodie/3x/connect_the_dots_happy.png
    - assets/hoodie/4x/connect_the_dots_happy.png
    - assets/hoodie/crossword_happy.png
    - assets/hoodie/2x/crossword_happy.png
    - assets/hoodie/3x/crossword_happy.png
    - assets/hoodie/4x/crossword_happy.png
    - assets/hoodie/draw_challenge_happy.png
    - assets/hoodie/2x/draw_challenge_happy.png
    - assets/hoodie/3x/draw_challenge_happy.png
    - assets/hoodie/4x/draw_challenge_happy.png
    - assets/hoodie/drawing_happy.png
    - assets/hoodie/2x/drawing_happy.png
    - assets/hoodie/3x/drawing_happy.png
    - assets/hoodie/4x/drawing_happy.png
    - assets/hoodie/fill_in_the_blanks_happy.png
    - assets/hoodie/2x/fill_in_the_blanks_happy.png
    - assets/hoodie/3x/fill_in_the_blanks_happy.png
    - assets/hoodie/4x/fill_in_the_blanks_happy.png
    - assets/hoodie/fill_number_happy.png
    - assets/hoodie/2x/fill_number_happy.png
    - assets/hoodie/3x/fill_number_happy.png
    - assets/hoodie/4x/fill_number_happy.png
    - assets/hoodie/first_word_happy.png
    - assets/hoodie/2x/first_word_happy.png
    - assets/hoodie/3x/first_word_happy.png
    - assets/hoodie/4x/first_word_happy.png
    - assets/hoodie/friend_word_happy.png
    - assets/hoodie/2x/friend_word_happy.png
    - assets/hoodie/3x/friend_word_happy.png
    - assets/hoodie/4x/friend_word_happy.png
    - assets/hoodie/guess_happy.png
    - assets/hoodie/2x/guess_happy.png
    - assets/hoodie/3x/guess_happy.png
    - assets/hoodie/4x/guess_happy.png
    - assets/hoodie/identify_happy.png
    - assets/hoodie/2x/identify_happy.png
    - assets/hoodie/3x/identify_happy.png
    - assets/hoodie/4x/identify_happy.png
    - assets/hoodie/identify_happy.png
    - assets/hoodie/2x/identify_happy.png
    - assets/hoodie/3x/identify_happy.png
    - assets/hoodie/4x/identify_happy.png
    - assets/hoodie/match_the_following_happy.png
    - assets/hoodie/2x/match_the_following_happy.png
    - assets/hoodie/3x/match_the_following_happy.png
    - assets/hoodie/4x/match_the_following_happy.png
    - assets/hoodie/memory_happy.png
    - assets/hoodie/2x/memory_happy.png
    - assets/hoodie/3x/memory_happy.png
    - assets/hoodie/4x/memory_happy.png
    - assets/hoodie/order_it_happy.png
    - assets/hoodie/2x/order_it_happy.png
    - assets/hoodie/3x/order_it_happy.png
    - assets/hoodie/4x/order_it_happy.png
    - assets/hoodie/quiz_happy.png
    - assets/hoodie/2x/quiz_happy.png
    - assets/hoodie/3x/quiz_happy.png
    - assets/hoodie/4x/quiz_happy.png
    - assets/hoodie/spin_wheel_happy.png
    - assets/hoodie/2x/spin_wheel_happy.png
    - assets/hoodie/3x/spin_wheel_happy.png
    - assets/hoodie/4x/spin_wheel_happy.png
    - assets/hoodie/tables_happy.png
    - assets/hoodie/2x/tables_happy.png
    - assets/hoodie/3x/tables_happy.png
    - assets/hoodie/4x/tables_happy.png
    - assets/hoodie/tap_home_happy.png
    - assets/hoodie/2x/tap_home_happy.png
    - assets/hoodie/3x/tap_home_happy.png
    - assets/hoodie/4x/tap_home_happy.png
    - assets/hoodie/tap_wrong_happy.png
    - assets/hoodie/2x/tap_wrong_happy.png
    - assets/hoodie/3x/tap_wrong_happy.png
    - assets/hoodie/4x/tap_wrong_happy.png 
    - assets/hoodie/true_or_false_happy.png
    - assets/hoodie/2x/true_or_false_happy.png
    - assets/hoodie/3x/true_or_false_happy.png
    - assets/hoodie/4x/true_or_false_happy.png
    
    #sad
    - assets/hoodie/reflex_sad.png
    - assets/hoodie/2x/reflex_sad.png
    - assets/hoodie/3x/reflex_sad.png
    - assets/hoodie/4x/reflex_sad.png
    - assets/hoodie/abacus_sad.png
    - assets/hoodie/2x/abacus_sad.png
    - assets/hoodie/3x/abacus_sad.png
    - assets/hoodie/4x/abacus_sad.png
    - assets/hoodie/bingo_sad.png
    - assets/hoodie/2x/bingo_sad.png
    - assets/hoodie/3x/bingo_sad.png
    - assets/hoodie/4x/bingo_sad.png
    - assets/hoodie/calculate_numbers_sad.png
    - assets/hoodie/2x/calculate_numbers_sad.png
    - assets/hoodie/3x/calculate_numbers_sad.png
    - assets/hoodie/4x/calculate_numbers_sad.png
    - assets/hoodie/casino_sad.png
    - assets/hoodie/2x/casino_sad.png
    - assets/hoodie/3x/casino_sad.png
    - assets/hoodie/4x/casino_sad.png
    - assets/hoodie/circle_words_sad.png
    - assets/hoodie/2x/circle_words_sad.png
    - assets/hoodie/3x/circle_words_sad.png
    - assets/hoodie/4x/circle_words_sad.png
    - assets/hoodie/clue_game_sad.png
    - assets/hoodie/2x/clue_game_sad.png
    - assets/hoodie/3x/clue_game_sad.png
    - assets/hoodie/4x/clue_game_sad.png
    - assets/hoodie/connect_the_dots_sad.png
    - assets/hoodie/2x/connect_the_dots_sad.png
    - assets/hoodie/3x/connect_the_dots_sad.png
    - assets/hoodie/4x/connect_the_dots_sad.png
    - assets/hoodie/crossword_sad.png
    - assets/hoodie/2x/crossword_sad.png
    - assets/hoodie/3x/crossword_sad.png
    - assets/hoodie/4x/crossword_sad.png
    - assets/hoodie/draw_challenge_sad.png
    - assets/hoodie/2x/draw_challenge_sad.png
    - assets/hoodie/3x/draw_challenge_sad.png
    - assets/hoodie/4x/draw_challenge_sad.png
    - assets/hoodie/drawing_sad.png
    - assets/hoodie/2x/drawing_sad.png
    - assets/hoodie/3x/drawing_sad.png
    - assets/hoodie/4x/drawing_sad.png
    - assets/hoodie/fill_in_the_blanks_sad.png
    - assets/hoodie/2x/fill_in_the_blanks_sad.png
    - assets/hoodie/3x/fill_in_the_blanks_sad.png
    - assets/hoodie/4x/fill_in_the_blanks_sad.png
    - assets/hoodie/fill_number_sad.png
    - assets/hoodie/2x/fill_number_sad.png
    - assets/hoodie/3x/fill_number_sad.png
    - assets/hoodie/4x/fill_number_sad.png
    - assets/hoodie/first_word_sad.png
    - assets/hoodie/2x/first_word_sad.png
    - assets/hoodie/3x/first_word_sad.png
    - assets/hoodie/4x/first_word_sad.png
    - assets/hoodie/friend_word_sad.png
    - assets/hoodie/2x/friend_word_sad.png
    - assets/hoodie/3x/friend_word_sad.png
    - assets/hoodie/4x/friend_word_sad.png
    - assets/hoodie/guess_sad.png
    - assets/hoodie/2x/guess_sad.png
    - assets/hoodie/3x/guess_sad.png
    - assets/hoodie/4x/guess_sad.png
    - assets/hoodie/identify_sad.png
    - assets/hoodie/2x/identify_sad.png
    - assets/hoodie/3x/identify_sad.png
    - assets/hoodie/4x/identify_sad.png
    - assets/hoodie/identify_sad.png
    - assets/hoodie/2x/identify_sad.png
    - assets/hoodie/3x/identify_sad.png
    - assets/hoodie/4x/identify_sad.png
    - assets/hoodie/match_the_following_sad.png
    - assets/hoodie/2x/match_the_following_sad.png
    - assets/hoodie/3x/match_the_following_sad.png
    - assets/hoodie/4x/match_the_following_sad.png
    - assets/hoodie/memory_sad.png
    - assets/hoodie/2x/memory_sad.png
    - assets/hoodie/3x/memory_sad.png
    - assets/hoodie/4x/memory_sad.png
    - assets/hoodie/order_it_sad.png
    - assets/hoodie/2x/order_it_sad.png
    - assets/hoodie/3x/order_it_sad.png
    - assets/hoodie/4x/order_it_sad.png
    - assets/hoodie/quiz_sad.png
    - assets/hoodie/2x/quiz_sad.png
    - assets/hoodie/3x/quiz_sad.png
    - assets/hoodie/4x/quiz_sad.png
    - assets/hoodie/spin_wheel_sad.png
    - assets/hoodie/2x/spin_wheel_sad.png
    - assets/hoodie/3x/spin_wheel_sad.png
    - assets/hoodie/4x/spin_wheel_sad.png
    - assets/hoodie/tables_sad.png
    - assets/hoodie/2x/tables_sad.png
    - assets/hoodie/3x/tables_sad.png
    - assets/hoodie/4x/tables_sad.png
    - assets/hoodie/tap_home_sad.png
    - assets/hoodie/2x/tap_home_sad.png
    - assets/hoodie/3x/tap_home_sad.png
    - assets/hoodie/4x/tap_home_sad.png
    - assets/hoodie/tap_wrong_sad.png
    - assets/hoodie/2x/tap_wrong_sad.png
    - assets/hoodie/3x/tap_wrong_sad.png
    - assets/hoodie/4x/tap_wrong_sad.png 
    - assets/hoodie/true_or_false_sad.png
    - assets/hoodie/2x/true_or_false_sad.png
    - assets/hoodie/3x/true_or_false_sad.png
    - assets/hoodie/4x/true_or_false_sad.png
    - assets/background_tile.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
