name: maui
description: Literacy application for children

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  image_picker:
  cupertino_icons: ^0.1.0
  sqflite: any
  uuid: ^1.0.3
  path_provider: ^0.4.0
  tuple: ^1.0.1
  json_annotation: ^1.1.0
  audioplayers: ^0.7.5
  fluttery:
    git:
      https://github.com/chimple/fluttery.git
  flutter_circular_chart: "^0.1.0"
  shared_preferences: ^0.4.2
  camera: 0.2.1
  nima: ^1.0.1
  flutter_local_notifications: ^0.3.7
  badge:
    git:
      https://github.com/chimple/Flutter-Badge.git
  intl: ^0.15.7
  intl_translation: ^0.17.0
  simple_permissions: ^0.1.6
  flutter_svg: ^0.5.1
  image: ^2.0.4
  flutter_redurx: ^0.4.3
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  video_player: "^0.5.4"
  build_runner: ^0.10.1
  json_serializable: ^1.2.1
  flutter_markdown: ^0.2.0
  tahiti:
    path: ../tahiti
  flores:
    path: ../flores

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/right.wav
    - assets/wrong.wav
    - assets/lion.ogg
    - assets/monkey.ogg
    - assets/duck.ogg
    - assets/fox.ogg
    - assets/rabbit.ogg
    
    - assets/tap.wav
    - assets/demo_video/
    - assets/videohelp.png
    - assets/database.db
    - assets/solo.nima
    - assets/solo.png
    - assets/chimple_logo.png
    - assets/father.png
    - assets/mother.png
    - assets/sister.png
    - assets/quack_header.png
    - assets/games.png
    - assets/profile.png
    - assets/quack.png
    - assets/news_feed.png
    - assets/messenger.png
    - assets/brother.png
    - assets/star.png
    - assets/star_gained.png
    - assets/apple.png
    - assets/Colors.png
    - assets/Flowers.png
    - assets/Fruits.png
    - assets/Clothes.png
    - assets/Fruits.json
    - assets/Clothes.json
    - assets/HouseItems.png
    - assets/Boy.png
    - assets/Body.png
    - assets/Scene.png
    - assets/Scene.json
    - assets/Colors.json
    - assets/Flowers.json
    - assets/HouseItems.json
    - assets/Shapes.json
    - assets/Boy.json
    - assets/Body.json
    - assets/Work.json
    - assets/Hospital.json
    - assets/Animals.json
    - assets/BedRoom.json
    - assets/Birds.json
    - assets/Work.png
    - assets/Hospital.png
    - assets/Animals.png
    - assets/BedRoom.png
    - assets/chat_Bot_Icon.png
    - assets/Birds.png
    - assets/apple.ogg
    - assets/dice_game/
    - assets/background_image/
    - assets/background_gif/Win_loop.gif
    - assets/chat_image/
    - assets/games.png
    - assets/chat.png
    - assets/chatBig.png
    - assets/chatSmall.png
    - assets/gameBig.png
    - assets/gameSmall.png
    - assets/story.png
    - assets/Shapes.png
    - assets/hoodie/
    - assets/hoodie_fb.png
    - assets/hoodie_bear.png
    - assets/koala_neutral.png
    - assets/koala_happy.png
    - assets/koala_sad.png
    - assets/animations/
    - assets/forward_button.png
    - assets/home_button.png
    - assets/dice.png
    - assets/wordgrid.png
    - assets/picture_sentence.png
    - assets/dice_happy.png
    - assets/wordgrid_happy.png
    - assets/picture_sentence_happy.png
    - assets/background_tile.png
    - assets/dice_sad.png
    - assets/wordgrid_sad.png
    - assets/picture_sentence_sad.png
    # dictionary
    - assets/dict/
    - assets/star_music.mp3
    - assets/stickers/pig/
    - assets/stickers/giraffe/
    - assets/stickers/monkey/
    - assets/stickers/doggie/
    - assets/stickers/carpie/
    - assets/stickers/emoguy/
    - assets/category/
    - assets/nima_animation/
    - assets/team animals.svg
    - assets/topic/
    - assets/masking/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: Bungee
      fonts:
        - asset: assets/fonts/Bungee-Regular.ttf
    - family: Chela one
      fonts:
        - asset: assets/fonts/ChelaOne-Regular.ttf
    - family: Gloria Hallelujah
      fonts:
        - asset: assets/fonts/GloriaHallelujah.ttf
    - family: Great vibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf
    - family: Homemade apple
      fonts:
        - asset: assets/fonts/HomemadeApple-Regular.ttf
    - family: Indie Flower
      fonts:
        - asset: assets/fonts/IndieFlower.ttf
    - family: Kirang Haerang
      fonts:
        - asset: assets/fonts/KirangHaerang-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Patrick Hand
      fonts:
        - asset: assets/fonts/PatrickHand-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Rock salt
      fonts:
        - asset: assets/fonts/RockSalt-Regular.ttf
    - family: Shadows into light
      fonts:
        - asset: assets/fonts/ShadowsIntoLight.ttf
